reader_writer:
		gcc -pthread -o ../bin/reader_writer semaphore/custom_sem.c problems/reader_writer.c 

producer_consumer:
		gcc -pthread -o ../bin/producer_consumer semaphore/custom_sem.c problems/producer_consumer.c 

dinning_philosopher:
		gcc -pthread -o ../bin/dinning_philosopher semaphore/custom_sem.c problems/dinning_philosopher.c
dinning_philosopher_odd_even:
		gcc -pthread -o ../bin/dinning_philosopher_odd_even semaphore/custom_sem.c problems/dinning_philosopher_odd_even.c
dinning_philosopher_last:
		gcc -pthread -o ../bin/dinning_philosopher_last semaphore/custom_sem.c problems/dinning_philosopher_last.c